export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const ADD_CART_FAIL = "ADD_CART_FAIL";

export const CART_ITEMS_REQUEST = "CART_ITEMS_REQUEST"
export const CART_ITEMS_SUCCESS = "CART_ITEMS_SUCCESS"
export const CART_ITEMS_FAIL = "CART_ITEMS_FAIL"

export const CART_ITEM_REMOVE_REQUEST = "CART_ITEM_REMOVE_REQUEST"
export const CART_ITEM_REMOVE_SUCCESS = "CART_ITEM_REMOVE_SUCCESS"
export const CART_ITEM_REMOVE_FAIL = "CART_ITEM_REMOVE_FAIL"

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS"
export const SAVE_PAYMENT = "SAVE_PAYMENT"