export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_SAVE_REQUEST = "ORDER_SAVE_REQUEST";


export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";


export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL'

export const TOTAL_ORDER_REQUEST = 'TOTAL_ORDER_REQUEST'
export const TOTAL_ORDER_SUCCESS = 'TOTAL_ORDER_SUCCESS'
export const TOTAL_ORDER_FAIL = 'TOTAL_ORDER_FAIL'